# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import library_inventory_pb2 as library__inventory__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17inventory_service.proto\x12\x0clibinventory\x1a\x17library_inventory.proto\"5\n\x11\x43reateBookRequest\x12 \n\x04\x62ook\x18\x01 \x01(\x0b\x32\x12.libinventory.Book\"5\n\x12\x43reateBookResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"b\n\x0fGetBookResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x04\x62ook\x18\x03 \x01(\x0b\x32\x12.libinventory.BookH\x00\x88\x01\x01\x42\x07\n\x05_book2\xaf\x01\n\x10InventoryService\x12Q\n\nCreateBook\x12\x1f.libinventory.CreateBookRequest\x1a .libinventory.CreateBookResponse\"\x00\x12H\n\x07GetBook\x12\x1c.libinventory.GetBookRequest\x1a\x1d.libinventory.GetBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKREQUEST._serialized_start=66
  _CREATEBOOKREQUEST._serialized_end=119
  _CREATEBOOKRESPONSE._serialized_start=121
  _CREATEBOOKRESPONSE._serialized_end=174
  _GETBOOKREQUEST._serialized_start=176
  _GETBOOKREQUEST._serialized_end=206
  _GETBOOKRESPONSE._serialized_start=208
  _GETBOOKRESPONSE._serialized_end=306
  _INVENTORYSERVICE._serialized_start=309
  _INVENTORYSERVICE._serialized_end=484
# @@protoc_insertion_point(module_scope)
