# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17library_inventory.proto\x12\x0clibinventory\"\xd1\x01\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x06\x61uthor\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x16\n\x0epublishingYear\x18\x04 \x01(\x05\x12,\n\x05genre\x18\x05 \x01(\x0e\x32\x18.libinventory.Book.GenreH\x01\x88\x01\x01\"<\n\x05Genre\x12\x0b\n\x07\x46ICTION\x10\x00\x12\r\n\tBIOGRAPHY\x10\x01\x12\x0b\n\x07HISTORY\x10\x02\x12\n\n\x06TRAVEL\x10\x03\x42\t\n\x07_authorB\x08\n\x06_genre\"\xb3\x01\n\rInventoryItem\x12\x17\n\x0finventoryNumber\x18\x01 \x01(\x05\x12!\n\x05oneOf\x18\x02 \x01(\x0b\x32\x12.libinventory.Book\x12\x37\n\x06status\x18\x03 \x01(\x0e\x32\".libinventory.InventoryItem.StatusH\x00\x88\x01\x01\"\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x42\t\n\x07_statusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=42
  _BOOK._serialized_end=251
  _BOOK_GENRE._serialized_start=170
  _BOOK_GENRE._serialized_end=230
  _INVENTORYITEM._serialized_start=254
  _INVENTORYITEM._serialized_end=433
  _INVENTORYITEM_STATUS._serialized_start=388
  _INVENTORYITEM_STATUS._serialized_end=422
# @@protoc_insertion_point(module_scope)
